<a href="https://colab.research.google.com/github/MisbahSarkawas/RailNexus/blob/main/RailNexus_Module2_Predictive_Intelligence.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

RailNexus — Module 2: Predictive Railway Intelligence

In [1]:

import os
import sys
import pandas as pd
import numpy as np

print("RAILNEXUS - MODULE 2 INSPECTION")
print("-" * 40)

print("Python version:", sys.version.split()[0])
print("Pandas version:", pd.__version__)
print("NumPy version:", np.__version__)

print("\nCurrent working directory:")
print(os.getcwd())

print("\nFiles available in the current directory:")
for item in os.listdir("."):
    print(item)

print("\nInspection completed.")

RAILNEXUS - MODULE 2 INSPECTION
----------------------------------------
Python version: 3.13.16
Pandas version: 2.2.3
NumPy version: 2.1.3

Current working directory:
/content

Files available in the current directory:
.config
sample_data

Inspection completed.

In [2]:

import os

print("RAILNEXUS - DATASET DISCOVERY")
print("-" * 40)

for root, dirs, files in os.walk("/content"):
    # Skip Colab configuration files
    dirs[:] = [d for d in dirs if d != ".config"]

    for file in files:
        path = os.path.join(root, file)
        print(path)

print("\nDataset discovery completed.")

RAILNEXUS - DATASET DISCOVERY
----------------------------------------
/content/sample_data/README.md
/content/sample_data/anscombe.json
/content/sample_data/california_housing_test.csv
/content/sample_data/mnist_test.csv
/content/sample_data/mnist_train_small.csv
/content/sample_data/california_housing_train.csv

Dataset discovery completed.

In [3]:

import sys
import pandas
import numpy

print("Python:", sys.version)
print("Pandas:", pandas.__version__)
print("NumPy:", numpy.__version__)

try:
    import sklearn
    import scipy
    import joblib

    print("Scikit-learn:", sklearn.__version__)
    print("SciPy:", scipy.__version__)
    print("Joblib:", joblib.__version__)

except ImportError as e:
    print("A package is missing:", e)

Python: 3.13.16 (main, Oct  1 2026, 15:40:24) [GCC 13.3.0]
Pandas: 2.2.3
NumPy: 2.1.3
Scikit-learn: 1.6.1
SciPy: 1.16.3
Joblib: 1.6.0

Phase A — Dataset Investigation

Project: RailNexus Module 2
Owner: Misbah Sarkawas

Current environment:
Python 3.13.16
Pandas 2.2.3
NumPy 2.1.3
Scikit-learn 1.6.1
SciPy 1.16.3
Joblib 1.6.0

Existing data inspection:
No railway dataset found in /content.
Only default Google Colab sample files were present.

Required prediction tasks:
1. Train-delay prediction
2. Passenger-demand prediction
3. Congestion and bottleneck prediction

Next action:
Verify candidate railway datasets, their sources,
licences, columns, targets, and limitations.
Do not train models until the data is inspected.

In [4]:

import os
import zipfile
import pandas as pd

folder = "/content"

# Extract the schedule ZIP if it has been uploaded
zip_path = os.path.join(folder, "train_schedule.csv.zip")

if os.path.exists(zip_path):
    with zipfile.ZipFile(zip_path, "r") as z:
        z.extractall("/content/railway_data")
    print("Schedule ZIP extracted.")
else:
    print("Upload train_schedule.csv.zip first.")

# Locate the train information CSV
info_path = os.path.join(folder, "train_info.csv")

if os.path.exists(info_path):
    info = pd.read_csv(info_path)
    print("\nTRAIN INFO")
    print("Shape:", info.shape)
    print("Columns:", info.columns.tolist())
    display(info.head())
else:
    print("Upload train_info.csv first.")

# Locate the extracted schedule CSV
schedule_path = "/content/railway_data/train_schedule.csv"

if os.path.exists(schedule_path):
    schedule = pd.read_csv(schedule_path)
    print("\nTRAIN SCHEDULE")
    print("Shape:", schedule.shape)
    print("Columns:", schedule.columns.tolist())
    display(schedule.head())
else:
    print("Check the extracted filename if the schedule CSV was not found.")

Schedule ZIP extracted.

TRAIN INFO
Shape: (11113, 5)
Columns: ['Train_No', 'Train_Name', 'Source_Station_Name', 'Destination_Station_Name', 'days']

,Train_No,Train_Name,Source_Station_Name,Destination_Station_Name,days
0,107,SWV-MAO-VLNK,SAWANTWADI ROAD,MADGOAN JN.,Saturday
1,108,VLNK-MAO-SWV,MADGOAN JN.,SAWANTWADI ROAD,Friday
2,128,MAO-KOP SPEC,MADGOAN JN.,CHHATRAPATI SHAHU MAHARAJ TERMINUS,Friday
3,290,PALACE ON WH,DELHI-SAFDAR JANG,DELHI-SAFDAR JANG,Wednesday
4,401,BSB BHARATDA,AURANGABAD,VARANASI JN.,Saturday

TRAIN SCHEDULE
Shape: (186074, 12)
Columns: ['SN', 'Train_No', 'Station_Code', '1A', '2A', '3A', 'SL', 'Station_Name', 'Route_Number', 'Arrival_time', 'Departure_Time', 'Distance']

,SN,Train_No,Station_Code,1A,2A,3A,SL,Station_Name,Route_Number,Arrival_time,Departure_Time,Distance
0,1,107,SWV,100,100,100,100,SAWANTWADI R,1,00:00:00,10:25:00,0
1,2,107,THVM,260,228,196,164,THIVIM,1,11:06:00,11:08:00,32
2,3,107,KRMI,345,296,247,198,KARMALI,1,11:28:00,11:30:00,49
3,4,107,MAO,490,412,334,256,MADGOAN JN.,1,12:10:00,00:00:00,78
4,1,108,MAO,100,100,100,100,MADGOAN JN.,1,00:00:00,20:30:00,0

In [5]:

import pandas as pd
import os

base = "/content/railway_data"

info_path = "/content/train_info.csv"
schedule_path = os.path.join(base, "train_schedule.csv")

info = pd.read_csv(info_path)
schedule = pd.read_csv(schedule_path)

for name, df in [
    ("TRAIN INFO", info),
    ("TRAIN SCHEDULE", schedule)
]:
    print(f"\n{'=' * 45}")
    print(name)
    print("=" * 45)

    print("\nColumn names and data types:")
    print(df.dtypes)

    print("\nMissing values per column:")
    print(df.isna().sum())

    print("\nDuplicate rows:", df.duplicated().sum())

    print("\nSample records:")
    display(df.head(3))

print("\nUnique train numbers in train_info:",
      info["Train_No"].nunique())

print("Unique train numbers in schedule:",
      schedule["Train_No"].nunique())

=============================================
TRAIN INFO
=============================================

Column names and data types:
Train_No                     int64
Train_Name                  object
Source_Station_Name         object
Destination_Station_Name    object
days                        object
dtype: object

Missing values per column:
Train_No                    0
Train_Name                  0
Source_Station_Name         0
Destination_Station_Name    0
days                        0
dtype: int64

Duplicate rows: 0

Sample records:

,Train_No,Train_Name,Source_Station_Name,Destination_Station_Name,days
0,107,SWV-MAO-VLNK,SAWANTWADI ROAD,MADGOAN JN.,Saturday
1,108,VLNK-MAO-SWV,MADGOAN JN.,SAWANTWADI ROAD,Friday
2,128,MAO-KOP SPEC,MADGOAN JN.,CHHATRAPATI SHAHU MAHARAJ TERMINUS,Friday

=============================================
TRAIN SCHEDULE
=============================================

Column names and data types:
SN                 int64
Train_No           int64
Station_Code      object
1A                 int64
2A                 int64
3A                 int64
SL                 int64
Station_Name      object
Route_Number       int64
Arrival_time      object
Departure_Time    object
Distance           int64
dtype: object

Missing values per column:
SN                0
Train_No          0
Station_Code      0
1A                0
2A                0
3A                0
SL                0
Station_Name      0
Route_Number      0
Arrival_time      0
Departure_Time    0
Distance          0
dtype: int64

Duplicate rows: 0

Sample records:

,SN,Train_No,Station_Code,1A,2A,3A,SL,Station_Name,Route_Number,Arrival_time,Departure_Time,Distance
0,1,107,SWV,100,100,100,100,SAWANTWADI R,1,00:00:00,10:25:00,0
1,2,107,THVM,260,228,196,164,THIVIM,1,11:06:00,11:08:00,32
2,3,107,KRMI,345,296,247,198,KARMALI,1,11:28:00,11:30:00,49

Unique train numbers in train_info: 11113
Unique train numbers in schedule: 11113

In [6]:

import pandas as pd
import os

info = pd.read_csv("/content/train_info.csv")
schedule = pd.read_csv(
    "/content/railway_data/train_schedule.csv"
)

# Standardize column-name whitespace
info.columns = info.columns.str.strip()
schedule.columns = schedule.columns.str.strip()

print("RAILNEXUS - DATA VALIDATION")
print("-" * 40)

# 1. Check train-number matching
info_trains = set(info["Train_No"].dropna())
schedule_trains = set(schedule["Train_No"].dropna())

print("Train numbers only in train_info:",
      len(info_trains - schedule_trains))

print("Train numbers only in schedule:",
      len(schedule_trains - info_trains))

print("Train numbers shared by both:",
      len(info_trains & schedule_trains))

# 2. Check schedule time formats
for col in ["Arrival_time", "Departure_Time"]:
    if col in schedule.columns:
        parsed = pd.to_datetime(
            schedule[col].astype(str),
            format="%H:%M:%S",
            errors="coerce"
        )

        print(f"\n{col}")
        print("Valid time values:", parsed.notna().sum())
        print("Invalid time values:", parsed.isna().sum())
        print("Examples:", schedule[col].head(5).tolist())

# 3. Check whether a train has multiple route records
if "Route_Number" in schedule.columns:
    routes = schedule.groupby("Train_No")[
        "Route_Number"
    ].nunique()

    print("\nTrains with multiple route numbers:",
          (routes > 1).sum())

print("\nValidation completed.")

RAILNEXUS - DATA VALIDATION
----------------------------------------
Train numbers only in train_info: 0
Train numbers only in schedule: 0
Train numbers shared by both: 11113

Arrival_time
Valid time values: 186074
Invalid time values: 0
Examples: ['00:00:00', '11:06:00', '11:28:00', '12:10:00', '00:00:00']

Departure_Time
Valid time values: 186074
Invalid time values: 0
Examples: ['10:25:00', '11:08:00', '11:30:00', '00:00:00', '20:30:00']

Trains with multiple route numbers: 0

Validation completed.

In [7]:

import pandas as pd
import os

input_path = "/content/railway_data/train_schedule.csv"
output_dir = "/content/railway_data/processed"
os.makedirs(output_dir, exist_ok=True)

schedule = pd.read_csv(input_path)
schedule.columns = schedule.columns.str.strip()

# Standardize text fields without changing original files
for col in ["Station_Code", "Station_Name"]:
    if col in schedule.columns:
        schedule[col] = schedule[col].astype("string").str.strip()

# Convert scheduled times into time objects
for col in ["Arrival_time", "Departure_Time"]:
    if col in schedule.columns:
        schedule[col] = pd.to_datetime(
            schedule[col].astype(str),
            format="%H:%M:%S",
            errors="coerce"
        ).dt.time

# Check the distance column
if "Distance" in schedule.columns:
    schedule["Distance"] = pd.to_numeric(
        schedule["Distance"], errors="coerce"
    )
    print("Missing distances:", schedule["Distance"].isna().sum())
    print("Negative distances:", (schedule["Distance"] < 0).sum())

# Save a processed copy
output_path = os.path.join(
    output_dir, "train_schedule_cleaned.csv"
)
schedule.to_csv(output_path, index=False)

print("\nProcessed dataset saved to:", output_path)
print("Rows and columns:", schedule.shape)
print("Duplicate rows:", schedule.duplicated().sum())
print("\nProcessed sample:")
display(schedule.head())

Missing distances: 0
Negative distances: 0

Processed dataset saved to: /content/railway_data/processed/train_schedule_cleaned.csv
Rows and columns: (186074, 12)
Duplicate rows: 0

Processed sample:

,SN,Train_No,Station_Code,1A,2A,3A,SL,Station_Name,Route_Number,Arrival_time,Departure_Time,Distance
0,1,107,SWV,100,100,100,100,SAWANTWADI R,1,00:00:00,10:25:00,0
1,2,107,THVM,260,228,196,164,THIVIM,1,11:06:00,11:08:00,32
2,3,107,KRMI,345,296,247,198,KARMALI,1,11:28:00,11:30:00,49
3,4,107,MAO,490,412,334,256,MADGOAN JN.,1,12:10:00,00:00:00,78
4,1,108,MAO,100,100,100,100,MADGOAN JN.,1,00:00:00,20:30:00,0

In [8]:

import pandas as pd

path = "/content/railway_data/processed/train_schedule_cleaned.csv"
df = pd.read_csv(path)

print("RAILNEXUS - TIMETABLE PROFILE")
print("-" * 40)

# 1. Check midnight values
for col in ["Arrival_time", "Departure_Time"]:
    if col in df.columns:
        midnight = (df[col].astype(str) == "00:00:00").sum()
        print(f"{col} midnight values: {midnight}")

# 2. Check station sequence ordering
df = df.sort_values(["Train_No", "SN"])

print("\nSchedule rows per train:")
print(df.groupby("Train_No").size().describe())

# 3. Check distance consistency within each train
if "Distance" in df.columns:
    df["Distance"] = pd.to_numeric(df["Distance"], errors="coerce")
    distance_changes = df.groupby("Train_No")["Distance"].agg(
        lambda x: (x.diff().dropna() < 0).sum()
    )
    print("\nTrains with decreasing distance values:",
          (distance_changes > 0).sum())

# 4. Inspect column names and examples
print("\nColumns:", df.columns.tolist())
display(df.head(10))

print("\nTimetable profiling completed.")

RAILNEXUS - TIMETABLE PROFILE
----------------------------------------
Arrival_time midnight values: 2003
Departure_Time midnight values: 1970

Schedule rows per train:
count    11113.000000
mean        16.743814
std         12.993123
min          2.000000
25%          8.000000
50%         15.000000
75%         22.000000
max        118.000000
dtype: float64

Trains with decreasing distance values: 0

Columns: ['SN', 'Train_No', 'Station_Code', '1A', '2A', '3A', 'SL', 'Station_Name', 'Route_Number', 'Arrival_time', 'Departure_Time', 'Distance']

,SN,Train_No,Station_Code,1A,2A,3A,SL,Station_Name,Route_Number,Arrival_time,Departure_Time,Distance
0,1,107,SWV,100,100,100,100,SAWANTWADI R,1,00:00:00,10:25:00,0
1,2,107,THVM,260,228,196,164,THIVIM,1,11:06:00,11:08:00,32
2,3,107,KRMI,345,296,247,198,KARMALI,1,11:28:00,11:30:00,49
3,4,107,MAO,490,412,334,256,MADGOAN JN.,1,12:10:00,00:00:00,78
4,1,108,MAO,100,100,100,100,MADGOAN JN.,1,00:00:00,20:30:00,0
5,2,108,KRMI,265,232,199,166,KARMALI,1,21:04:00,21:06:00,33
6,3,108,THVM,355,304,253,202,THIVIM,1,21:26:00,21:28:00,51
7,4,108,SWV,515,432,349,266,SAWANTWADI R,1,22:25:00,00:00:00,83
8,1,128,MAO,100,100,100,100,MADGOAN JN.,1,19:40:00,19:40:00,0
9,2,128,KRMI,265,232,199,166,KARMALI,1,20:18:00,20:20:00,33

Timetable profiling completed.

In [9]:

import pandas as pd

path = "/content/railway_data/processed/train_schedule_cleaned.csv"
df = pd.read_csv(path)

df = df.sort_values(["Train_No", "SN"]).copy()

for col in ["Arrival_time", "Departure_Time"]:
    df[f"{col}_is_midnight"] = (
        df[col].astype(str).str.strip() == "00:00:00"
    )

# Identify first and last recorded stops per train
first_rows = df.groupby("Train_No").head(1)
last_rows = df.groupby("Train_No").tail(1)

print("MIDNIGHT TIME INVESTIGATION")
print("-" * 40)

for col in ["Arrival_time", "Departure_Time"]:
    flag = f"{col}_is_midnight"

    print(f"\n{col}")
    print("Total midnight values:", df[flag].sum())
    print("Midnight values at first stop:",
          first_rows[flag].sum())
    print("Midnight values at last stop:",
          last_rows[flag].sum())

    print("\nExamples of midnight records:")
    display(
        df.loc[
            df[flag],
            ["Train_No", "SN", "Station_Name", col]
        ].head(10)
    )

print("\nInvestigation completed.")

MIDNIGHT TIME INVESTIGATION
----------------------------------------

Arrival_time
Total midnight values: 2003
Midnight values at first stop: 1951
Midnight values at last stop: 4

Examples of midnight records:

      Train_No  SN  Station_Name Arrival_time
0          107   1  SAWANTWADI R     00:00:00
4          108   1   MADGOAN JN.     00:00:00
990       4831   1   JODHPUR JN.     00:00:00
1328      5715   1  NEW JALPAIGU     00:00:00
1330      5716   1    KISHANGANJ     00:00:00
1332      5719   1   KATIHAR JN.     00:00:00
1343      5720   1  SILIGURI JN.     00:00:00
1870      6081   1    COIMBATORE     00:00:00
1874      6082   1      POLLACHI     00:00:00
1878      6412   1  DELHI-SAFDAR     00:00:00

Departure_Time
Total midnight values: 1970
Midnight values at first stop: 0
Midnight values at last stop: 1955

Examples of midnight records:

      Train_No  SN  Station_Name Departure_Time
3          107   4   MADGOAN JN.       00:00:00
7          108   4  SAWANTWADI R       00:00:00
1011      4831  22   HARIDWAR JN       00:00:00
1329      5715   2    KISHANGANJ       00:00:00
1331      5716   2  NEW JALPAIGU       00:00:00
1342      5719  11  SILIGURI JN.       00:00:00
1353      5720  11   KATIHAR JN.       00:00:00
1873      6081   4      POLLACHI       00:00:00
1877      6082   4    COIMBATORE       00:00:00
1898      6412  21      PAYYANUR       00:00:00

Investigation completed.

In [10]:

import pandas as pd
import os

input_path = "/content/railway_data/processed/train_schedule_cleaned.csv"
output_dir = "/content/railway_data/processed"

df = pd.read_csv(input_path)
df = df.sort_values(["Train_No", "SN"]).copy()

# Numeric distance and route sequence
df["Distance"] = pd.to_numeric(df["Distance"], errors="coerce")
df["SN"] = pd.to_numeric(df["SN"], errors="coerce")

# Flag midnight values without changing the original times
df["arrival_midnight_flag"] = (
    df["Arrival_time"].astype(str) == "00:00:00"
).astype(int)

df["departure_midnight_flag"] = (
    df["Departure_Time"].astype(str) == "00:00:00"
).astype(int)

# Record the previous stop's distance for each train
df["previous_distance_km"] = (
    df.groupby("Train_No")["Distance"].shift(1)
)

df["distance_since_previous_stop_km"] = (
    df["Distance"] - df["previous_distance_km"]
)

# Identify the first and last scheduled stops
df["is_first_stop"] = (
    df.groupby("Train_No")["SN"].transform("min") == df["SN"]
).astype(int)

df["is_last_stop"] = (
    df.groupby("Train_No")["SN"].transform("max") == df["SN"]
).astype(int)

output_path = os.path.join(
    output_dir, "timetable_features.csv"
)
df.to_csv(output_path, index=False)

print("Timetable features saved:", output_path)
print("Rows:", len(df))
print("Columns:", len(df.columns))
print("\nNew feature summary:")
display(df[[
    "Train_No", "SN", "Station_Code", "Distance",
    "distance_since_previous_stop_km",
    "arrival_midnight_flag", "departure_midnight_flag",
    "is_first_stop", "is_last_stop"
]].head(10))

print("\nMissing previous distances:",
      df["previous_distance_km"].isna().sum())

Timetable features saved: /content/railway_data/processed/timetable_features.csv
Rows: 186074
Columns: 18

New feature summary:

,Train_No,SN,Station_Code,Distance,distance_since_previous_stop_km,arrival_midnight_flag,departure_midnight_flag,is_first_stop,is_last_stop
0,107,1,SWV,0,NaN,1,0,1,0
1,107,2,THVM,32,32.0,0,0,0,0
2,107,3,KRMI,49,17.0,0,0,0,0
3,107,4,MAO,78,29.0,0,1,0,1
4,108,1,MAO,0,NaN,1,0,1,0
5,108,2,KRMI,33,33.0,0,0,0,0
6,108,3,THVM,51,18.0,0,0,0,0
7,108,4,SWV,83,32.0,0,1,0,1
8,128,1,MAO,0,NaN,0,0,1,0
9,128,2,KRMI,33,33.0,0,0,0,0

Missing previous distances: 11113

In [11]:

import pandas as pd

path = "/content/indian_railway_delays_dataset.csv"

df = pd.read_csv(path)

print("Shape:", df.shape)
print("Columns:", df.columns.tolist())
print("\nMissing values:")
print(df.isna().sum())
print("\nSample records:")
display(df.head())

Shape: (10, 6)
Columns: ['Train_Name', 'Route', 'Scheduled_Arrival', 'Actual_Arrival', 'Delay_Minutes', 'Date']

Missing values:
Train_Name           0
Route                0
Scheduled_Arrival    0
Actual_Arrival       0
Delay_Minutes        0
Date                 0
dtype: int64

Sample records:

,Train_Name,Route,Scheduled_Arrival,Actual_Arrival,Delay_Minutes,Date
0,Rajdhani Express,Delhi–Mumbai,10:00,10:45,45,2024-10-01
1,Shatabdi Express,Jaipur–Delhi,07:00,07:05,5,2024-10-02
2,Duronto Express,Mumbai–Kolkata,09:30,10:15,45,2024-10-03
3,Garib Rath Express,Delhi–Lucknow,11:00,11:40,40,2024-10-04
4,Tejas Express,Mumbai–Goa,06:30,06:50,20,2024-10-05

In [12]:
import pandas as pd

df.columns = df.columns.str.strip()

df["Scheduled_Arrival"] = pd.to_datetime(
    df["Scheduled_Arrival"], format="%H:%M"
)
df["Actual_Arrival"] = pd.to_datetime(
    df["Actual_Arrival"], format="%H:%M"
)

df["Calculated_Delay_Minutes"] = (
    df["Actual_Arrival"] - df["Scheduled_Arrival"]
).dt.total_seconds() / 60

print("Dataset rows:", len(df))
print("\nDelay comparison:")
display(df[[
    "Train_Name",
    "Scheduled_Arrival",
    "Actual_Arrival",
    "Delay_Minutes",
    "Calculated_Delay_Minutes"
]])

print(
    "\nDo recorded delays match calculated delays?",
    (df["Delay_Minutes"] == df["Calculated_Delay_Minutes"]).all()
)

Dataset rows: 10

Delay comparison:

,Train_Name,Scheduled_Arrival,Actual_Arrival,Delay_Minutes,Calculated_Delay_Minutes
0,Rajdhani Express,1900-01-01 10:00:00,1900-01-01 10:45:00,45,45.0
1,Shatabdi Express,1900-01-01 07:00:00,1900-01-01 07:05:00,5,5.0
2,Duronto Express,1900-01-01 09:30:00,1900-01-01 10:15:00,45,45.0
3,Garib Rath Express,1900-01-01 11:00:00,1900-01-01 11:40:00,40,40.0
4,Tejas Express,1900-01-01 06:30:00,1900-01-01 06:50:00,20,20.0
5,Humsafar Express,1900-01-01 13:00:00,1900-01-01 13:20:00,20,20.0
6,Jan Shatabdi Express,1900-01-01 08:45:00,1900-01-01 08:50:00,5,5.0
7,Intercity Express,1900-01-01 09:15:00,1900-01-01 09:25:00,10,10.0
8,Sampark Kranti Express,1900-01-01 17:30:00,1900-01-01 18:10:00,40,40.0
9,Vande Bharat Express,1900-01-01 06:00:00,1900-01-01 06:10:00,10,10.0

Do recorded delays match calculated delays? True

In [13]:
%pip -q install huggingface_hub